version: '3.9'

volumes:
    nightlife_mysql:
    nightlife_test_mysql:

services:
  mysql8:
    image: mysql:8.2
    environment:
        - MYSQL_ROOT_PASSWORD=nightlife
        - MYSQL_DATABASE=nightlife
    env_file:
        - ./.env
    volumes:
        - nightlife_mysql:/var/lib/mysql
    ports:
        - '3310:3306'
    restart: unless-stopped
    stdin_open: true
    command:
        ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    healthcheck:
        test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
        timeout: 5s
        retries: 10

  mysql8-test:
    image: mysql:8.2
    environment:
        - MYSQL_ROOT_PASSWORD=nightlife
        - MYSQL_DATABASE=nightlife_test
    env_file:
        - ./.env.test
    volumes:
        - nightlife_test_mysql:/var/lib/mysql
    ports:
        - '3311:3306'
    restart: unless-stopped
    stdin_open: true
    command:
        ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
        